import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
// import { useState } from 'react';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Testing Next.jx 14 SSR',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /* const [menuOpen, setMenuOpen] = useState(false);

  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  }; */

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col text-neutral-900">
          {/* Header */}
          {/* <header
            className={`bg-gray-800 text-white p-4 md:p-6 md:flex md:justify-between md:items-center${
              menuOpen ? ' flex-col' : ''
            }`}
          > */}
          <header className="bg-gray-800 text-white p-4 md:p-6 md:flex md:justify-between md:items-center">
            <div className="flex justify-between items-center w-full md:w-auto">
              <h1 className="text-3xl font-bold cursor-pointer">
                <Link href="/">Testing Next.jx 14 SSR</Link>
              </h1>
              <button /* onClick={toggleMenu} */ className="block md:hidden">
                {/* {!menuOpen ? ( */}
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    fillRule="evenodd"
                    d="M3 6.75A.75.75 0 0 1 3.75 6h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 6.75ZM3 12a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 12Zm0 5.25a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75a.75.75 0 0 1-.75-.75Z"
                    clipRule="evenodd"
                  />
                </svg>
                {/* ) : (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    fill="currentColor"
                    className="w-6 h-6"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M5.47 5.47a.75.75 0 0 1 1.06 0L12 10.94l5.47-5.47a.75.75 0 1 1 1.06 1.06L13.06 12l5.47 5.47a.75.75 0 1 1-1.06 1.06L12 13.06l-5.47 5.47a.75.75 0 0 1-1.06-1.06L10.94 12 5.47 6.53a.75.75 0 0 1 0-1.06Z"
                      clip-rule="evenodd"
                    />
                  </svg>
                )} */}
              </button>
            </div>
            <nav className="block md:flex w-full md:w-auto">
              <ul
                /* hidden={!menuOpen} */
                className="hidden md:flex flex-col md:flex-row space-y-2 md:space-y-0 md:space-x-4 mt-4 md:mt-0 text-lg"
              >
                <li>
                  <Link href="/" className="hover:underline">
                    Inicio
                  </Link>
                </li>
                <li>
                  <Link href="/users" className="hover:underline">
                    Usuarios
                  </Link>
                </li>
                <li>
                  <Link href="/posts" className="hover:underline">
                    Posts
                  </Link>
                </li>
                <li>
                  <Link href="/albums" className="hover:underline">
                    Álbumes
                  </Link>
                </li>
              </ul>
            </nav>
          </header>

          {/* Main Content */}
          <main className="flex-grow p-4 md:p-6 lg:mx-auto lg:max-w-screen-md xl:max-w-screen-lg">
            {children}
          </main>

          {/* Footer */}
          <footer className="bg-gray-800 text-white p-4">
            <p className="text-center">
              © 2024 Testing Next.jx 14 SSR. Todos los derechos reservados.
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
